name:                gloss-bump
version:             0.1.0.0
github:              "ncaq/gloss-bump"
license:             MIT
author:              "ncaq"
maintainer:          "ncaq@ncaq.net"
copyright:           "© ncaq"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ncaq/gloss-bump#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- random

library:
  source-dirs: src

executables:
  gloss-bump-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloss-bump

tests:
  gloss-bump-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloss-bump
